### PR TITLE
refactor: make serde an optional dependency

### LINKED ISSUE #126: Make serde an optional dependency
From the example I have the impression that serde is not actually needed in order to use this crate. If I am correct, then it would be better to specify serde as an optional dependency and compile it only if the user wants it. It would be like this:

`Cargo.toml`
```toml
[dependencies]
serde = {version = "1.0.55", optional = true}

[features]
default = ["serde"]
```

This way, if the user does not want serde, all what it has to do is to put this in his `Cargo.toml`

```toml
[dependencies.csv]
version = "1"
default-features = false
```

### PR DESCRIPTION
**Pull request by lojewalo**
See title! Closes #126.

My concerns:

1. `Cargo.toml` took a beating with required features.
2. Doc comments with serde are ugly.

I think 2 is fine, but 1 feels awful.

### CODE REVIEW

**Comment by jkcclemens** [comment]
I think the rustfmt output looks much worse in this case, but I added a commit just for the sake of CI passing.

**Comment by Kerollmops** [comment]
I just tried you branch and removed all the `[[xxx]] required-features = ["serde"]` configurations lines and it worked without complaining. Do you think those are necessary?

**Comment by jkcclemens** [comment]
Running `cargo test --no-default-features` failed without it when I tried. Did you attempt that?

**Comment by Kerollmops** [comment]
Hum... You are right :) Just tried.

**Comment by jbaum98** [comment]
What's the status of this PR? I would like this feature, so if there's anything I can do to get this merged let me know.

**Comment by devashishdxt** [comment]
@BurntSushi Are there any plans to merge this PR?

**Comment by BurntSushi** [comment]
> @BurntSushi Are there any plans to merge this PR?

Perhaps eventually.

**Comment by devashishdxt** [comment]
> > @BurntSushi Are there any plans to merge this PR?
> 
> Perhaps eventually.

Are there any changes required before merging this?

**Pull request closed without merging**
