### PR TITLE
derive Clone

### PR DESCRIPTION
**Pull request by kindlychung**
Not sure if it's the right thing to do, but judging from these lines in your example:

```
    let new_csv_rdr = || csv::Reader::from_string(data);

    let mut index_data = io::Cursor::new(Vec::new());
    create_index(new_csv_rdr(), index_data.by_ref()).unwrap();
    let mut index = Indexed::open(new_csv_rdr(), index_data).unwrap();
```

using `new_csv_rdr.clone()` would be more natural and less hassle.

### CODE REVIEW

**Comment by kindlychung** [comment]
Ah, more work to do. Take it as a tiny idea then, 😄

**Comment by kindlychung** [comment]
Got this error:

```
/Users/kaiyin/.multirust/toolchains/nightly/cargo/git/checkouts/rust-csv-9757b77efa53e506/patch-1/src/reader.rs:102:5: 102:17 error: the trait bound `reader::State: std::clone::Clone` is not satisfied [E0277]
/Users/kaiyin/.multirust/toolchains/nightly/cargo/git/checkouts/rust-csv-9757b77efa53e506/patch-1/src/reader.rs:102     state: State,
                                                                                                                        ^~~~~~~~~~~~
/Users/kaiyin/.multirust/toolchains/nightly/cargo/git/checkouts/rust-csv-9757b77efa53e506/patch-1/src/reader.rs:96:10: 96:15 note: in this expansion of #[derive_Clone] (defined in /Users/kaiyin/.multirust/toolchains/nightly/cargo/git/checkouts/rust-csv-9757b77efa53e506/patch-1/src/reader.rs)
/Users/kaiyin/.multirust/toolchains/nightly/cargo/git/checkouts/rust-csv-9757b77efa53e506/patch-1/src/reader.rs:102:5: 102:17 help: run `rustc --explain E0277` to see a detailed explanation
/Users/kaiyin/.multirust/toolchains/nightly/cargo/git/checkouts/rust-csv-9757b77efa53e506/patch-1/src/reader.rs:102:5: 102:17 note: required by `std::clone::Clone::clone`
error: aborting due to previous error
error: Could not compile `csv`.
```

**Comment by kindlychung** [comment]
Ok, now Reader should be clonable.

**Comment by kindlychung** [comment]
Another problem: `the following trait bounds were not satisfied: `std::fs::File : std::clone::Clone``. Strange that this has escaped the eyes of the compiler.

**Comment by BurntSushi** [comment]
Could you please not make arbitrary formatting changes? I'm happy to consider them in a separate PR, but as it stands, it's not easy for me to see what the meaty part of this PR is.

**Comment by kindlychung** [comment]
Ah, that's rustfmt at work. Every time I save a file in vim, it gets formatted. I will turn it off, but I guess it's too late for this PR. Sorry.

**Comment by BurntSushi** [comment]
Sorry, but I'm not merging as is.

**Comment by kindlychung** [comment]
No problem, it's probably not a good idea anyway.

**Comment by iamsebastian** [comment]
Could this PR be closed than? Would make the repo a bit more clean.

**Pull request closed without merging**
